name = "RandomNet"
uuid = "0c82d87f-20dd-4ddc-9845-e6567e1dbcfe"
authors = ["Carson C Chow <ccc1685@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Distributions = "0.25.102"
Plots = "1.39.0"
LinearAlgebra = "1.9.3"

